name: TiTok
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.7.15
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - ncurses=6.5
  - openssl=3.0.17
  - pthread-stubs=0.3
  - python=3.9.18
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.5
      - braceexpand==0.1.7
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.1.8
      - datasets==3.6.0
      - diffusers==0.35.1
      - dill==0.3.8
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - filelock==3.13.1
      - frozenlist==1.7.0
      - fsspec==2024.10.0
      - ftfy==6.3.1
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - hf-xet==1.1.9
      - huggingface-hub==0.34.4
      - idna==3.10
      - importlib-metadata==8.7.0
      - iopath==0.1.10
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - networkx==3.2.1
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - open-clip-torch==3.1.0
      - packaging==25.0
      - pandas==2.3.2
      - pillow==11.3.0
      - pip==24.2
      - platformdirs==4.4.0
      - portalocker==3.2.0
      - propcache==0.3.2
      - protobuf==6.32.0
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pyarrow-hotfix==0.7
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.9.1
      - requests==2.32.5
      - safetensors==0.6.2
      - scipy==1.13.1
      - sentry-sdk==2.35.2
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.8
      - sympy==1.14.0
      - termcolor==3.1.0
      - timm==1.0.19
      - tokenizers==0.20.3
      - torch==2.8.0
      - torch-fidelity==0.3.0
      - torchinfo==1.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.46.2
      - triton==3.4.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.21.3
      - wcwidth==0.2.13
      - webdataset==0.2.100
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
      - tensorboard==2.20.0
